# Generated by Django 5.1.4 on 2025-07-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_string', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=11, unique=True)),
                ('saved', models.BooleanField(default=False)),
            ],
        ),
    ]
