# Generated by Django 5.1.4 on 2025-07-30 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excelfileinfo',
            old_name='date_string',
            new_name='directory',
        ),
    ]
