# Generated by Django 5.1.4 on 2025-08-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_tracker', '0002_rename_date_string_excelfileinfo_directory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelfileinfo',
            name='directory',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='excelfileinfo',
            name='name',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterUniqueTogether(
            name='excelfileinfo',
            unique_together={('directory', 'name')},
        ),
    ]
