# Generated by Django 5.1.4 on 2025-08-05 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_tracker', '0003_alter_excelfileinfo_directory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excelfileinfo',
            options={'ordering': ['-name']},
        ),
    ]
