# Generated by Django 5.1.4 on 2025-08-05 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_tracker', '0004_alter_excelfileinfo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excelfileinfo',
            options={'ordering': ['-directory', '-name']},
        ),
    ]
