# Generated by Django 5.1.4 on 2025-09-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_tracker', '0005_alter_excelfileinfo_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excelfileinfo',
            old_name='saved',
            new_name='is_contracts_saved',
        ),
        migrations.AddField(
            model_name='excelfileinfo',
            name='is_prices_saved',
            field=models.BooleanField(default=False),
        ),
    ]
