# Generated by Django 5.1.4 on 2025-05-22 12:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strike_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiration_date', models.DateField()),
                ('contract_type', models.CharField(choices=[('SELL', 'اختیار فروش'), ('BUY', 'اختیار خرید')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('group', models.CharField(choices=[('ATMTV', 'صنعت خودرو و ساخت قطعات'), ('BSCMTLS', 'صنعت فلزات اساسی'), ('CHMCLS', 'صنعت شیمیایی'), ('PTRLMPRDCTS', 'صنعت فرآورده\u200cهای نفتی، کک و سوخت هسته\u200cای'), ('PPRPRDCTS', 'صنعت محصولات کاغذی'), ('PHRMCTCLS', 'صنعت دارویی'), ('CEMENT', 'صنعت سیمان، آهک و گچ'), ('TLCMNCTN', 'صنعت مخابرات'), ('BANKS', 'صنعت بانک\u200cها و موسسات اعتباری'), ('PTRCHMCLS', 'صنعت پتروشیمی'), ('AGRCLTR', 'صنعت کشاورزی'), ('TRNSPRTTN', 'صنعت حمل و نقل'), ('MCHNRY', 'صنعت ماشین\u200cآلات و تجهیزات'), ('BLDNGMTRLS', 'صنعت ساختمان و مصالح ساختمانی'), ('NNFRSMTLS', 'صنعت فلزات غیرآهنی'), ('OILGAS', 'صنعت نفت و گاز'), ('CRMCSGLS', 'صنعت سرامیک و شیشه'), ('OTHER', 'دیگر گروه ها')], default='OTHER', max_length=11)),
                ('is_in_option_chain', models.BinaryField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OptionPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tse_downloader.option')),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tse_downloader.stock'),
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tse_downloader.stock')),
            ],
            options={
                'unique_together': {('stock', 'timestamp')},
            },
        ),
    ]
