# Generated by Django 5.1.4 on 2025-07-01 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tse_downloader', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='option',
            unique_together={('stock', 'strike_price', 'expiration_date', 'contract_type')},
        ),
    ]
