# Generated by Django 5.1.4 on 2025-07-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tse_downloader', '0002_alter_option_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='option',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='option',
            constraint=models.UniqueConstraint(fields=('stock', 'strike_price', 'expiration_date', 'contract_type'), name='unique_option_contract'),
        ),
    ]
