# Generated by Django 5.1.4 on 2025-09-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tse_downloader', '0003_alter_option_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionprice',
            name='price',
        ),
        migrations.AddField(
            model_name='optionprice',
            name='buy_bid_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='optionprice',
            name='last_deal_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='optionprice',
            name='sell_bid_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
