# Generated by Django 5.1.4 on 2025-09-29 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tse_downloader', '0004_remove_optionprice_price_optionprice_buy_bid_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionprice',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='tse_downloader.option'),
        ),
    ]
