# Generated by Django 5.1.4 on 2025-10-09 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tse_downloader', '0005_alter_optionprice_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='tse_downloader.stock'),
        ),
    ]
