# Generated by Django 5.1.4 on 2025-10-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tse_downloader', '0006_alter_option_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionprice',
            name='deal_count',
            field=models.IntegerField(default=0, max_length=7),
        ),
        migrations.AddField(
            model_name='optionprice',
            name='deal_value',
            field=models.IntegerField(default=0, max_length=14),
        ),
        migrations.AddField(
            model_name='optionprice',
            name='deal_volume',
            field=models.IntegerField(default=0, max_length=13),
        ),
    ]
