# Generated by Django 5.1.4 on 2025-10-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tse_downloader', '0007_optionprice_deal_count_optionprice_deal_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionprice',
            name='deal_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='optionprice',
            name='deal_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='optionprice',
            name='deal_volume',
            field=models.IntegerField(default=0),
        ),
    ]
