# Generated by Django 5.1.4 on 2025-11-08 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tse_downloader', '0008_alter_optionprice_deal_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockprice',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='tse_downloader.stock'),
        ),
    ]
