# Generated by Django 5.1.4 on 2026-05-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tse_downloader', '0009_alter_stockprice_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionprice',
            name='deal_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='optionprice',
            name='deal_value',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='optionprice',
            name='deal_volume',
            field=models.BigIntegerField(default=0),
        ),
    ]
